main: com.github.dimitrivasiliadis.tipoftheday.TipOfTheDay
version: ${git.commit.id.describe-short}
name: tipoftheday
api-version: 1.20
author: Meech

depend: []

commands:
  tip:
    description: fetch tips
    usage: /<command>
    aliases:
      - totd
      - news